/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ask1.h"
#include <math.h>	//gia tin pow()

float *
metre_1_svc(X_array *argp, struct svc_req *rqstp)
{
	static float  result;

	printf("Metre function called...\n");

	int i, sum=0;
	
	for(i=0;i<argp->X_size;i++)
		sum+=  pow(argp->X.X_val[i], 2);
	
	result = pow(sum, 0.5);
	
	return &result;
}

int *
inner_product_1_svc(XY_array *argp, struct svc_req *rqstp)
{
	static int  result = 0;

	printf("Inner product function called...\n");

	int i, j, sum = 0;
	
	for(i=0;i<argp->XY_size/2;i++) {
		result += argp->XY.XY_val[i] * argp->XY.XY_val[argp->XY_size/2+i];
	}
		
	return &result;
}

float *
averagex_1_svc(X_array *argp, struct svc_req *rqstp)
{
	static float  result;

	printf("Average function for X[] called...\n");
	
	float sum=0;
	int i;

	for(i=0;i<argp->X_size;i++)
		sum+=argp->X.X_val[i];
		
	result=sum/argp->X_size;
	
	return &result;
}

float *
averagey_1_svc(Y_array *argp, struct svc_req *rqstp)
{
	static float  result;

	printf("Average function for Y[] called...\n");
	
	float sum=0;
	int i;

	for(i=0;i<argp->Y_size;i++)
		sum+=argp->Y.Y_val[i];
		
	result=sum/argp->Y_size;
	
	return &result;
}

rXY *
product_1_svc(r_times_X_Y *argp, struct svc_req *rqstp)
{
	static rXY  result;

	printf("r*(X[] + Y[]) function called...\n");

	result.prod.prod_len=argp->X_Y_size;
	result.prod.prod_val=(float *)malloc(argp->X_Y_size*sizeof(float));
	
	int i;
	
	for(i=0;i<argp->X_Y_size;i++)
		result.prod.prod_val[i]=argp->r*argp->X_Y.X_Y_val[i];

	return &result;
}
